In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:

response = requests.get('https://btech-data-analytics.github.io/bridgerland-technical-college/bookstore.html').text

In [3]:
soup = BeautifulSoup(response, 'html.parser')

In [4]:
soup

<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://www.w3schools.com/w3css/4/w3.css" rel="stylesheet"/>
<link href="style.css" rel="stylesheet"/>
<title>Bob's Bookstore</title>
</head>
<body>
<div class="w3-bar w3-blue-grey w3-large" style="padding: 0rem 8rem 0rem 8rem">
<a href="/bridgerland-technical-college/home.html"><img class="" src="bobs_bookstore_white.png" style="max-height: 2.8rem;"/></a>
<a class="w3-bar-item w3-button w3-right" href="/bridgerland-technical-college/bookstore.html">Store</a>
<a class="w3-bar-item w3-button w3-right" href="/bridgerland-technical-college/contact.html">Contact</a>
<a class="w3-bar-item w3-button w3-right" href="/bridgerland-technical-college/about.html">About</a>
</div>
<div class="w3-container" style="max-width: 1000px;margin: auto;">
<h1>Books for Sale</h1>
<table class="w3-table-all w3-hoverable w3-small">
<thead>
<tr>
<th>ISBN</th>
<th>Title</th>
<th>Author</th>
<th>Language</th>
<th>Pages</th>
<th>Topic</th>
<th>Price</th>
<th></th>
</tr>
</thead>
<tr class="book">
<td>978-1234567890</td>
<td>Whiskers of Wisdom: Tales from Feline Philosophers</td>
<td>Penelope Wainwright</td>
<td>English</td>
<td>256</td>
<td>Cats</td>
<td>$19.99</td>
<td><button>Buy now</button></td>
</tr>
<tr class="book">
<td>978-2345678901</td>
<td>Purrfectly Pawesome: A Cat's Life</td>
<td>Jasper Sterling</td>
<td>English</td>
<td>192</td>
<td>Cats</td>
<td>$15.99</td>
<td><button>Buy now</button></td>
</tr>
<tr class="book">
<td>978-3456789012</td>
<td>Cat Tales: Adventures in Whiskerland</td>
<td>Penelope Wainwright</td>
<td>English</td>
<td>320</td>
<td>Cats</td>
<td>$21.99</td>
<td><button>Buy now</button></td>
</tr>
<tr class="book">
<td>978-4567890123</td>
<td>The Enigmatic Paws: Mysteries of Meowville</td>
<td>Maximilian Thorne</td>
<td>English</td>
<td>288</td>
<td>Cats</td>
<td>$17.99</td>
<td><button>Buy now</button></td>
</tr>
<tr class="book">
<td>978-5678901234</td>
<td>Cats in Wonderland</td>
<td>Isadora Harrington</td>
<td>English</td>
<td>224</td>
<td>Cats</td>
<td>$16.99</td>
<td><button>Buy now</button></td>
</tr>
<tr class="book">
<td>978-6789012345</td>
<td>Whisker Wisdom: Life Lessons from Feline Sages</td>
<td>Penelope Wainwright</td>
<td>English</td>
<td>288</td>
<td>Cats</td>
<td>$20.99</td>
<td><button>Buy now</button></td>
</tr>
<tr class="book">
<td>978-7890123456</td>
<td>Catnip Chronicles: A Purrfect Journey</td>
<td>Jasper Sterling</td>
<td>English</td>
<td>192</td>
<td>Cats</td>
<td>$14.99</td>
<td><button>Buy now</button></td>
</tr>
<tr class="book">
<td>978-8901234567</td>
<td>Cat-astrophe: Tales of Misadventures</td>
<td>Celeste Nightshade</td>
<td>English</td>
<td>240</td>
<td>Cats</td>
<td>$18.99</td>
<td><button>Buy now</button></td>
</tr>
<tr class="book">
<td>978-9012345678</td>
<td>The Cat's Whisker: A Feline Fantasy</td>
<td>Penelope Wainwright</td>
<td>English</td>
<td>208</td>
<td>Cats</td>
<td>$16.99</td>
<td><button>Buy now</button></td>
</tr>
<tr class="book">
<td>978-0123456789</td>
<td>Fur and Friendship: Stories of Feline Companions</td>
<td>Seraphina Montague</td>
<td>English</td>
<td>176</td>
<td>Cats</td>
<td>$12.99</td>
<td><button>Buy now</button></td>
</tr>
<tr class="book">
<td>978-1234567890</td>
<td>Tails of Loyalty: Canine Chronicles</td>
<td>Benjamin Barkley</td>
<td>English</td>
<td>256</td>
<td>Dogs</td>
<td>$29.99</td>
<td><button>Buy now</button></td>
</tr>
<tr class="book">
<td>978-2345678901</td>
<td>Pawsitive Adventures: A Dog's Journey</td>
<td>Sophie Shepherd</td>
<td>English</td>
<td>192</td>
<td>Dogs</td>
<td>$25.99</td>
<td><button>Buy now</button></td>
</tr>
<tr class="book">
<td>978-3456789012</td>
<td>Barking Wisdom: Lessons from Wise Canines</td>
<td>Oliver Obedience</td>
<td>English</td>
<td>320</td>
<td>Dogs</td>
<td>$21.99</td>
<td><button>Buy now</button></td>
</tr>
<tr class="book">
<td>978-4567890123</td>
<td>Dogged Determination: Stories of Resilient Pooches</td>
<td>Ruby Ruffington</td>
<td>English</td>
<td>288</td>
<td>Dogs</td>
<td>$27.99</td>
<td><button>Buy now</button></td>
</tr>
<tr class="book">
<td>978-5678901234</td>
<td>The Bark Brigade: Canine Heroes Among Us</td>
<td>Benjamin Barkley</td>
<td>English</td>
<td>224</td>
<td>Dogs</td>
<td>$26.99</td>
<td><button>Buy now</button></td>
</tr>
</table>
</div>
<footer class="page-footer">
<div class="footer-content">
<p>© 2023 Bob's Bookstore</p>
<ul class="social-icons">
<li><a href="#"><img alt="Facebook" src="facebook.png"/></a></li>
<li><a href="#"><img alt="Twitter" src="twitter.png"/></a></li>
<li><a href="#"><img alt="Instagram" src="instagram.png"/></a></li>
</ul>
</div>
</footer>
</body>
</html>

In [5]:
soup.find('table').find_all('tr', class_='book')

[<tr class="book">
 <td>978-1234567890</td>
 <td>Whiskers of Wisdom: Tales from Feline Philosophers</td>
 <td>Penelope Wainwright</td>
 <td>English</td>
 <td>256</td>
 <td>Cats</td>
 <td>$19.99</td>
 <td><button>Buy now</button></td>
 </tr>,
 <tr class="book">
 <td>978-2345678901</td>
 <td>Purrfectly Pawesome: A Cat's Life</td>
 <td>Jasper Sterling</td>
 <td>English</td>
 <td>192</td>
 <td>Cats</td>
 <td>$15.99</td>
 <td><button>Buy now</button></td>
 </tr>,
 <tr class="book">
 <td>978-3456789012</td>
 <td>Cat Tales: Adventures in Whiskerland</td>
 <td>Penelope Wainwright</td>
 <td>English</td>
 <td>320</td>
 <td>Cats</td>
 <td>$21.99</td>
 <td><button>Buy now</button></td>
 </tr>,
 <tr class="book">
 <td>978-4567890123</td>
 <td>The Enigmatic Paws: Mysteries of Meowville</td>
 <td>Maximilian Thorne</td>
 <td>English</td>
 <td>288</td>
 <td>Cats</td>
 <td>$17.99</td>
 <td><button>Buy now</button></td>
 </tr>,
 <tr class="book">
 <td>978-5678901234</td>
 <td>Cats in Wonderland</td>
 <td>Isadora Harrington</td>
 <td>English</td>
 <td>224</td>
 <td>Cats</td>
 <td>$16.99</td>
 <td><button>Buy now</button></td>
 </tr>,
 <tr class="book">
 <td>978-6789012345</td>
 <td>Whisker Wisdom: Life Lessons from Feline Sages</td>
 <td>Penelope Wainwright</td>
 <td>English</td>
 <td>288</td>
 <td>Cats</td>
 <td>$20.99</td>
 <td><button>Buy now</button></td>
 </tr>,
 <tr class="book">
 <td>978-7890123456</td>
 <td>Catnip Chronicles: A Purrfect Journey</td>
 <td>Jasper Sterling</td>
 <td>English</td>
 <td>192</td>
 <td>Cats</td>
 <td>$14.99</td>
 <td><button>Buy now</button></td>
 </tr>,
 <tr class="book">
 <td>978-8901234567</td>
 <td>Cat-astrophe: Tales of Misadventures</td>
 <td>Celeste Nightshade</td>
 <td>English</td>
 <td>240</td>
 <td>Cats</td>
 <td>$18.99</td>
 <td><button>Buy now</button></td>
 </tr>,
 <tr class="book">
 <td>978-9012345678</td>
 <td>The Cat's Whisker: A Feline Fantasy</td>
 <td>Penelope Wainwright</td>
 <td>English</td>
 <td>208</td>
 <td>Cats</td>
 <td>$16.99</td>
 <td><button>Buy now</button></td>
 </tr>,
 <tr class="book">
 <td>978-0123456789</td>
 <td>Fur and Friendship: Stories of Feline Companions</td>
 <td>Seraphina Montague</td>
 <td>English</td>
 <td>176</td>
 <td>Cats</td>
 <td>$12.99</td>
 <td><button>Buy now</button></td>
 </tr>,
 <tr class="book">
 <td>978-1234567890</td>
 <td>Tails of Loyalty: Canine Chronicles</td>
 <td>Benjamin Barkley</td>
 <td>English</td>
 <td>256</td>
 <td>Dogs</td>
 <td>$29.99</td>
 <td><button>Buy now</button></td>
 </tr>,
 <tr class="book">
 <td>978-2345678901</td>
 <td>Pawsitive Adventures: A Dog's Journey</td>
 <td>Sophie Shepherd</td>
 <td>English</td>
 <td>192</td>
 <td>Dogs</td>
 <td>$25.99</td>
 <td><button>Buy now</button></td>
 </tr>,
 <tr class="book">
 <td>978-3456789012</td>
 <td>Barking Wisdom: Lessons from Wise Canines</td>
 <td>Oliver Obedience</td>
 <td>English</td>
 <td>320</td>
 <td>Dogs</td>
 <td>$21.99</td>
 <td><button>Buy now</button></td>
 </tr>,
 <tr class="book">
 <td>978-4567890123</td>
 <td>Dogged Determination: Stories of Resilient Pooches</td>
 <td>Ruby Ruffington</td>
 <td>English</td>
 <td>288</td>
 <td>Dogs</td>
 <td>$27.99</td>
 <td><button>Buy now</button></td>
 </tr>,
 <tr class="book">
 <td>978-5678901234</td>
 <td>The Bark Brigade: Canine Heroes Among Us</td>
 <td>Benjamin Barkley</td>
 <td>English</td>
 <td>224</td>
 <td>Dogs</td>
 <td>$26.99</td>
 <td><button>Buy now</button></td>
 </tr>]

In [8]:
isbn = []
book = []
author = []
language = []
pages = []
topic = []
price = []
for books in soup.find('table').find_all('tr', class_= 'book'):
    isbn.append(books.find_all('td')[0].text)
    book.append(books.find_all('td')[1].text)
    author.append(books.find_all('td')[2].text)
    language.append(books.find_all('td')[3].text)
    pages.append(books.find_all('td')[4].text)
    topic.append(books.find_all('td')[5].text)
    price.append(books.find_all('td')[6].text)

In [9]:
df = pd.DataFrame({
    'ISBN': isbn,
    'Book': book,
    'Author': author,
    'Language': language,
    'Pages': pages,
    'Topic': topic,
    'Price': price
})

In [10]:
df['Pages'] = pd.to_numeric(df['Pages'], errors="coerce")

In [14]:
df["Price"] = (
    df["Price"]
      .str.replace("$", "", regex=False)
      .astype(float)
)

In [15]:
df['Author'].value_counts()

Author
Penelope Wainwright    4
Jasper Sterling        2
Benjamin Barkley       2
Maximilian Thorne      1
Isadora Harrington     1
Celeste Nightshade     1
Seraphina Montague     1
Sophie Shepherd        1
Oliver Obedience       1
Ruby Ruffington        1
Name: count, dtype: int64

In [16]:
df['Topic'].value_counts()

Topic
Cats    10
Dogs     5
Name: count, dtype: int64

In [17]:
round(df.groupby('Topic').agg({'Price': 'mean'}), 2)

       Price
Topic
Cats   17.79
Dogs   26.59

In [19]:
round(df.groupby('Topic').agg({'Pages': 'mean'}), 2)

       Pages
Topic
Cats   238.4
Dogs   256.0